additional_properties: {}
apiVersion: 2022-10-01-preview
extended_location: null
location: westeurope
name: database
properties:
  containers:
  - name: database
    properties:
      environmentVariables:
      - name: MYSQL_DATABASE
        value: woodytoys
      - name: MYSQL_USER
        value: admin
      - name: MYSQL_ROOT_PASSWORD
        value: admin
      - name: MYSQL_PASSWORD
        value: admin
      image: cradminii2tm2g2.azurecr.io/internal/database:latest
      ports:
      - port: 3306
        protocol: TCP
      resources:
        requests:
          cpu: 1.0
          memoryInGB: 1.5
      volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: databasevolume
  imageRegistryCredentials:
  - server: cradminii2tm2g2.azurecr.io
    username: CRAdminII2TM2G2
    
  initContainers: []
  osType: Linux
  restartPolicy: OnFailure
  sku: Standard
  subnetIds:
  - id: /subscriptions/1a2f4643-9291-403c-a431-af74ac27bd92/resourceGroups/RG_AdminII_2TM2-2/providers/Microsoft.Network/virtualNetworks/Vnet_AdminII_2TM2-2_vnet/subnets/DATABASE
  volumes:
  - name: databasevolume
    azureFile:
      sharename: databasefs
      storageAccountName: databasefs
      storageAccountKey: 57zpIoYLQ0tPEP9EWWBA8PL4hbTBrYAh1qlfSYa16Jm4seuWwnbY6psmrkR60YFtRyMfRDw+To0Q+AStM80dWA==
  dnsConfig:
    nameServers:
    - 10.0.0.212
tags: {}
type: Microsoft.ContainerInstance/containerGroups
