version: "3.3"
services:
  private_resolver:
    build: private/resolver/.
    container_name: private_resolver
    networks:
      - trusted
  private_soa:
    build: private/SOA/.
    container_name: private_soa
    networks:
      - trusted
  client:
    image: busybox
    networks:
      - enterprise
networks:
  trusted:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.208/28
  enterprise:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/25
