version: "3.3"
services:
  private_resolver:
    build: private/resolver/.
    container_name: private_resolver
    networks:
      - trusted
    ports:
      - "10.10.0.209:53:53/tcp"
      - "10.10.0.209:53:53/udp"
  private_soa:
    build: private/SOA/.
    container_name: private_soa
    networks:
      trusted:
        ipv4_address: "10.10.0.211"
  private_web:
    build: private/web/.
    container_name: intranetwoodytoys
    networks:
      - trusted
    ports:
      - "10.10.0.209:80:80"
  database:
    build: private/db/.
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      dbnet:
        ipv4_address: "10.10.0.226"
    environment:
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    restart: always
    volumes:
      - ./private/db/databasesWoodytoys:/docker-entrypoint-initdb.d
  mail:
    build: public/mail/.
    container_name: mail-server
    networks:
      - dmz
  client:
    image: busybox
    networks:
      - enterprise
networks:
  trusted:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.208/28
          gateway: 10.10.0.209
  enterprise:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/25
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.192/28
          gateway: 10.10.0.193
  dbnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.224/29
          gateway: 10.10.0.225
