version: "3.3"
services:
  private_resolver:
    build: private/resolver/.
    container_name: private_resolver
    networks:
      - trusted
    ports:
      - "10.10.0.209:53:53/tcp"
      - "10.10.0.209:53:53/udp"
  private_soa:
    build: private/SOA/.
    container_name: private_soa
    networks:
      - trusted
  mail:
    build: public/mail/.
    container_name: mail-server
    networks:
      - dmz
    ports:
      - "10.10.0.193:25:25"
      - "10.10.0.193:110:110"
      - "10.10.0.193:143:143"
    command: tail -F anything
  client:
    image: busybox
    networks:
      - enterprise
networks:
  trusted:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.208/28
          gateway: 10.10.0.209
  enterprise:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/25
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.192/28
          gateway: 10.10.0.193
