version: "3.1"
services:
  web:
    container_name: testwoodytoys
    image: my
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - .local-env

    links:
      - database
  database:
    container_name: database
    image: testmysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"

    env_file:
      - .local-env
#    environment:
#      MYSQL_DATABASE: MYSQL_DATABASE
#      MYSQL_USER: MYSQL_USER
#      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
#      MYSQL_PASSWORD: MYSQL_PASSWORD
    restart: always
    volumes:
      - ./db/databasesWoodytoys:/docker-entrypoint-initdb.d


