version: "3.1"
services:
  web:
    container_name: testwoodytoys
    image: my
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      #- "8080:8080"

    
    links:
      - database
  database:
    container_name: database
    image: testmysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    restart: always
    volumes:
      - ./db/databasesWoodytoys:/docker-entrypoint-initdb.d


